第1回講習資料
UECTechShinkan/web-workshop-2024 pull request #1
Opened 2024-05-12 06:07 UTC by e-chan1007

- 環境構築
- Gitリポジトリをフォーク・クローン
- Markdownを書く
- コミット

2024-05-12 08:09 UTC, e-chan1007 commented
だいたい書いた

2024-05-14 11:09 UTC, sushi-chaaaan commented on part-1/handouts/1_installation.md
> +- `Run this(these two) command in your terminal to add Homebrew to your PATH:` と表示された場合は、その下に表示されているコマンドをコピー&ペーストして実行してからターミナルを開き直してください。
```suggestion
- `Run this(these two) command in your terminal to add Homebrew to your PATH:` と表示された場合は、その下に表示されているコマンドをコピー&ペーストして実行してからターミナルを開き直してください。
  - ここに関しては、不安ならTAを呼んでください。
```

2024-05-14 12:31 UTC, sushi-chaaaan commented
レビュー途中やめにしてたの今思い出しました、残りをみます

2024-05-14 15:00 UTC, sushi-chaaaan requested changes
概ねLGTMです！ホームディレクトリの部分はもうちょっと例があるとわかりやすいかもしれません。

2024-05-14 15:00 UTC, sushichan044 commented on part-1/handouts/1_installation.md
> +- `Run this(these two) command in your terminal to add Homebrew to your PATH:` と表示された場合は、その下に表示されているコマンドをコピー&ペーストして実行してからターミナルを開き直してください。
例を示すかTAを呼んでもらうかどっちかにしたほうが良さそう

2024-05-14 15:00 UTC, sushichan044 commented on part-1/handouts/2_prepare-files.md
> +まずは、開発用のディレクトリ(フォルダー)を用意してください。このとき、ディレクトリ名には**日本語をはじめとする全角文字を使わない**ように注意してください[^1]。
多分ホームディレクトリ直下に指定したほうが進めるのが楽そうです。WindowsとMacそれぞれでスクショがあってもいいかもしれない

2024-05-16 07:22 UTC, e-chan1007 commented
ちょっと加筆

2024-05-16 07:26 UTC, sushi-chaaaan approved these changes
LGTMです！ありがとうございます 🙇

2024-05-16 07:28 UTC, merged