第2回コンテンツ
UECTechShinkan/web-workshop-2024 pull request #3
Opened 2024-05-20 16:13 UTC by sushi-chaaaan

2024-05-21 07:15 UTC, sushi-chaaaan commented
先にGitHub CLI入れてもらう

2024-05-22 12:36 UTC, sushi-chaaaan commented
@y-chan 
GitHubCLIのめっちゃ丁寧な入れ方(初回の資料を参考)を書いて欲しいです
- 鍵の管理はCLIに丸投げする選択肢でお願いします
- ファイル名はおまかせにします
- 最後に参加者のPC再起動させてください

2024-05-23 07:05 UTC, sushi-chaaaan commented
このあと演習＋GitHub Pagesへの公開が生えてきます

2024-05-23 07:05 UTC, sushi-chaaaan commented
@e-chan1007 一旦1章＋付録部分までのレビューをお願いできますか？

2024-05-23 07:11 UTC, e-chan1007 requested changes

2024-05-23 07:11 UTC, e-chan1007 commented on part-2/handouts/1_what_is_html.md
> +また、属性値に文字列を指定する場合は両端にクオート(`'`)をつけることを忘れないでください。(忘れると構文エラーになります。)
```suggestion
また、属性値に文字列を指定する場合は両端にダブルクオート(`"`)をつけることを忘れないでください。(忘れると構文エラーになります。)
```
構文上は問題ないとはいえ、この後の説明で属性値を`" "`で囲ってるのでそっちで統一したほうがいい気もします

2024-05-23 07:12 UTC, sushi-chaaaan commented on part-2/handouts/1_what_is_html.md
> +また、属性値に文字列を指定する場合は両端にクオート(`'`)をつけることを忘れないでください。(忘れると構文エラーになります。)
表記揺れしてますね、気づいていませんでした。
ありがとうございます。

2024-05-23 09:05 UTC, e-chan1007 approved these changes

2024-05-23 09:07 UTC, merged